spring:
  application:
    name: Hotel-Service
  config:
    import: optional:configserver:http://localhost:8085
server:
  port: 8082

spring.datasource.url: jdbc:postgresql://localhost:5432/Spring_micro
spring.datasource.username: postgres
spring.datasource.password: root		

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true

okta:
  oauth2:
    issuer: https://dev-29575430.okta.com/oauth2/default
    audience: api://default